name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: actions/checkout@v2
        with:
          ref: stage

      - name: validate before release
        run: |
          npm ci --no-save
          npm run lint
          npm run lint:md
          npm run test
        env:
          CI: true

      - name: rebase stage
        uses: cirrus-actions/rebase@1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: 2
