name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: validate before release
        run: |
          npm ci --no-save
          npm run lint
          npm run lint:md
          npm run test
        env:
          CI: true

      - name: push staging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout stage
          git pull --rebase origin master
          git push origin +stage
