name: Troubleshooting Github Actions

on: [push, pull_request]

jobs:
  troubleshooting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - run: printenv

      # https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"

      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: publish to npm
        run: |
          npx json -I -f package.json -e 'this.version="PR-${PR}--${COMMIT}"'
          cat package.json
        env:
          PR: ${{ github.event.pull_request.number }}
          COMMIT: ${{ github.event.pull_request.sha }}

